### ISSUE TITLE
 Add GET Authorisation to File Storage

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2609]
## Description
Integrating the policy-based authz used elsewhere in Magda with the new file storage system for GET access.

## Acceptance Criteria
- A file in storage api can have a record id / aspect id combination stored against it
- When a user makes a GET for a file, the storage API looks up whether the user is allowed to access that aspect of that record in the registry. If so it lets it through, if not it doesn't.

## Technical Notes
- @kring already kinda did this over at https://github.com/terriajs/magda
- This might be possible using minio metadata

### TODO
- [ ] When uploading, insert recordId to the magda-registry
- [ ] When GET-ing, make a request to registry with the recordId and userId
- [ ] If recordId is undefined, send the file through
- [ ] If recordId is defined, check if user can access the registry, and send the file through accordingly

## Out of Scope
- Authentication without the registry... we'll have to think about how that would work / what situation that would work in.
- Write access - this is only for reads
