### ISSUE TITLE
Clean up for 0.0.57 Release

### ISSUE THREAD

**Issue by AlexGilleran** [magda-io/magda#2896]
## Description
We should release what we've got so far, it's been a while.

## What we need to do

- [x] Update magda-config config.yaml comments so that they match the new options
- [x] Test out upgrade on a clone of data.gov.au, make sure that still works
- [x] Upgrade guide including upgrading helm3, cert manager etc
- [x] Doco for using `set-password` script
- [x] Doco for using API keys
(WIP)

**Comment by t83714** [comment]
All done
