### ISSUE TITLE
Allow user to access distribution by versions

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2915]
## Description
At this moment, when a new version distribution replaces/supersedes an existing distribution, a version in [version aspect](https://github.com/magda-io/magda/blob/666e70bcbee9cab62fe1e3a51f031abee2ab03b4/magda-registry-aspects/version.schema.json#L17) will be created but we still can't pull the previous version data file / external download link easily (unless looking up from history API --- which could be hard).

Also, at this moment, the old uploaded file will be deleted during the cleanup process after the `replace/supersede`. And the metadata of the new distribution will be copied and overwritten the old one.

### Solutions:
- [x] We will make All registry APIs that create / changes / updates the data should return the `eventId` of the event created for the operation (#2983). 
- [x] Relevant bug fixes: #2976 #2977  
- [x] When submitting a dataset, we should try to tag the current version with relevant EventId  (#2980). In this way, we can retrieve any version of the distribution data via Registry's [time travel API](https://dev.magda.io/api/v0/apidocs/index.html#api-Registry_Record_History-GetV0RegistryRecordsRecordidHistoryEventid)
- [x] Superseded data files will not be deleted anymore during the cleanup process. We will keep tracking superseded data files in `versions` aspect to avoid superseded data files being deleted (#2981 )
- [x] We then can implement UI Changes that allow the user to access the distribution page of a different distribution version by pulling versioned record data from Registry's [time travel API] at frontend. (#2982 #3000)
