### ISSUE TITLE
Upgrade DGA Site cluster & nodes to `1.16.13-gke.401` and Upgrade to Magda v0.0.57

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#2984]
### Upgrade DGA Site cluster & nodes to `1.16.13-gke.401` and Upgrade to Magda v0.0.57

According to GKE's email, we need to upgrade DGA Site cluster & nodes to `1.16.13-gke.401` because of a recently discovered [vulnerability in the Linux kernel](https://www.openwall.com/lists/oss-security/2020/09/03/3).

DGA site's cluster API is still on 1.14 and node is currently on 1.12 --- probably good timing to make it more up to date.

Since we probably unavoidable have to introduce some downtime, we probably should upgrade DGA to Magda v0.0.57 as well.

The DGA site is still 0.0.56 which is not compatible with k8s 1.16 and Google is actually start to upgrade clusters to 1.16 from **6th Oct 2020** (according to an email I received from Google).

### Tasks Required:
- [x] Make migration plan regarding requirement above (By COB 28th Sep 2020)
- [x] Make a clone of the existing DGA cluster and Test the migration plan for any potential issues (By COB 30th Sep 2020)
- [x] Negotiate upgrade timeframe with DTA
- [x] Perform the migration according to the migration plan (By 4th Oct 2020)

**Comment by t83714** [comment]
Here is the plan:
- Upgrade the cluster to 1.15 (currently, 1.14). Take around 10 mins
- Upgrade the node pools to 1.15 (currently, 1.12). Take around 50 mins. Default settings: max-surge-upgrade=1 & max-unavailable-upgrade=0  
- Uninstall Cert Manager (no way to upgrade without uninstall as current version 0.10.0 is far to old)
  - Delete anything found by `kubectl get Issuers,ClusterIssuers,Certificates,CertificateRequests,Orders,Challenges --all-namespaces`
  - `helm2 delete cert-manager --purge` 
  - delete all related CRDs via `kubectl delete -f https://github.com/jetstack/cert-manager/releases/download/v0.10.0/cert-manager.yaml` it's too old thus there is no separate cards release. Any errors can be ignored.
  - As we manually create `certificate` object, the whole process should not impact ingress tls.
- Install cert-manager v1.12
  - Install CRDs: `kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager-legacy.crds.yaml` (we still on 1.15 thus have to use legacy one)
  - `helm install cert-manager jetstack/cert-manager --namespace cert-manager --version v1.0.2`
  - create secret in cert-manager namespace
  - Install cert-issuer [here](https://github.com/magda-io/magda-config-data.gov.au/tree/master/cert-issuer) (with API version update). 
- Migrate Magda Helm2 deployment to Helm3
  - Run run migration script. Before the final apply, `certificate` object should be removed from manifest --- it's API version is too old. 
  - run helm 2to3 tool
  - modify [config.yaml](https://github.com/magda-io/magda-config-data.gov.au/blob/master/config.yaml) set `registry-api` & `search-api` to still use `0.0.56-RC6` & turn of indexer. Registry & search API still has accessible during the migration.
  - Once DB migration script is done & helm upgrade is complete. Rerun `helm upgrade` with indexer turned on and remove image tag setting for `registry-api`. This will start the reindexing process. As search API still use v56 image, the user still has access to full old index data while the reindexing the new index is in progress.
  - Once indexing is done, remove image tag for search api and `helm upgrade` again.
- Upgrade the cluster to 1.16. Take around 10 mins
- Upgrade the node pools to 1.16. Take around 10 mins
- Pull off maintenance notice card on DGA homepage
