### ISSUE TITLE
Tidy up non-core helm charts handles global image config

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3229]
### Tidy up non-core helm charts handles global image config

We have the following image config:
- `.Values.defaultImage`: individual chart's default image config.
  - `repository` is set to `docker.io/data61`
  - `tag` is set to `.Chart.Version`
  - `pullPolicy` is set to `IfNotPresent`
  - `imagePullSecret` is set to `false`
- `.Values.image`: individual chart's own image runtime config.
- `.Values.global.image`: for overriding image config of all sub charts. 
  - It's priority is lower than the 3 below
- `.Values.global.connectors.image`: for overriding image config of all connectors charts 
- `.Values.global.minions.image`: for overriding image config of all minions charts 
- `.Values.global.urlProcessors.image`: for overriding image config of all urlProcessors charts 

Each of the image config can have the following fields:
- `repository`: e.g. `docker.io/data61`
- `tag`: Sub module version e.g. `0.0.57-0`
  - `tag` field is not available to all types of image config. And only available to (and will be used for) the followings:
    - `.Values.image`
    - `.Values.global.image`
    - And when there is no other image config available, `.Chart.Version` will be used as default value.
- `pullPolicy`: image pull policy e.g.`IfNotPresent`
- `imagePullSecret`: can be either:
  - a list of pull secret names 
  - or a string that is one pull secret name
  - or boolean `false` which presents no pull secret is set / provided.

To avoid confusion and make it more consistent across all Magda core charts & plugins, we will make the following changes.
- For backward compatibility reason, `imagePullSecret` will still be supported. But we will auto check the following fields:
  - `pullSecret`
  - `pullSecrets`
  - `imagePullSecrets`
  - We still can passing either string, list of string or boolean `false` type as before.
- When set, `.Values.image` always has top priority. i.e. if it's set, its value will be the final value.
- When `.Values.image` is not set:
  - If no any other image config (e.g. `.Values.global.image`, `.Values.global.connectors.image` etc.) has been set, the chart's default image config (`.Values.defaultImage`) will be used.
  - When `.Values.global.image` is set, its value will only be used if `magdaModuleType` of the chart is `core`.
    - We will only set the `magdaModuleType` of charts in Magda's core repo to `core`.
  - When `.Values.global.connectors.image` is set, its value will only be used if `magdaModuleType` of the chart is `connector`.
  - When `.Values.global.minions.image` is set, its value will only be used if `magdaModuleType` of the chart is `minion`.
  - When `.Values.global.urlProcessors.image` is set, its value will only be used if `magdaModuleType` of the chart is `urlProcessor`.

> Here, `magdaModuleType` is an annotation set to Chart.yaml.

### Todo:
- [x] Implement above logic as Helm chart template in chart `magda-common`. They are:
  - [x]  `magda.imagePullSecrets`
  - [x] `magda.image`
  - [x] `magda.imagePullPolicy`
- [x] Use above templates to replace all relevant logic in magda repo charts
- [x] Use above templates to update all auth plugins
- [x] Use above templates to update all connectors
- [x] Use above templates to update all minions

**Comment by t83714** [comment]
closed via PR: https://github.com/magda-io/magda/pull/3240
