### ISSUE TITLE
Alternative way of serving region files

### ISSUE THREAD

**Issue by t83714** [magda-io/magda#3541]
### Alternative way of serving region files

Our [indexer module](https://github.com/magda-io/magda/tree/main/deploy/helm/internal-charts/indexer) and frontend map-based filter require region files to supply information on all supported regions.

We offer a list of default region files via config here:
https://github.com/magda-io/magda/blob/9876e04c1ed5ed4b8c6068d28dd0b605e095f718/magda-scala-common/src/main/resources/common.conf#L92

Users can configure those default region files via indexer Helm chart config (via `appConfig`, any config field can reached).

Those files are served from our AWS storage bucket. 

We have the following issues with the current setup:
- There is a cost involved when serving those files
- We need to turn off the storage bucket service due to internal account consolidation

### Proposed New Solution
- Move default region files to a public repo and serve from the GitHub release
  - according to [here](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#distributing-large-binaries) and [here](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas), there is no limit on the total size of a release, nor bandwidth usage. 
  - The only limit is "Each file included in a release must be under 2 GiB"
  - Free plan repo itself will have 10GB storage and 10GB transfer (repo transfer)
- internal premium projects use GCS

### Tasks
- [x] Create a public repo and manage region files using [Git Large File Storage (Git LFS)](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage) due to size of each file
- [x] ~Create CI workshop to auto-release default region files~ manually release for now
- [x] Update Indexer Helm Chart document to make it clearer and encourage users to use their own region files that served from their own infrastructure
- [x] Update default region files URL for indexer & release a new version

**Comment by t83714** [comment]
first release here: https://github.com/magda-io/magda-region-mappings/releases/tag/v1.0.0

**Comment by staffordsmith83** [comment]
Working to create new repo for default region mapping files
